### ISSUE TITLE
Record type for PureScript isn't quite right

### ISSUE THREAD

**Issue by garyb** [hakonrossebo/functional-programming-babelfish#1]
What you have there is a record inside a data type, records are first class so a type synonym would probably be a better example there:

```
type Point = { x :: Int, y :: Int}
```

**Comment by hakonrossebo** [comment]
Thanks, corrected. Am I correct that Haskell does not have this?

**Comment by garyb** [comment]
Yeah, that's right. When you do:

``` haskell
data Point = Point { x :: Int, y :: Int}
```

in Haskell, it's not really a record - it's a data constructor with named fields. That means that it also introduces accessor functions `x :: Point -> Int` and `y :: Point -> Int` in the current scope, and does allow pattern matching and stuff, but it's not quite the same thing as a record. You can also do things like this:

``` haskell 
data Point 
  = Point2D { x2 :: Int, y2 :: Int }
  | Pont3D { x3 :: Int, y3 :: Int, z3 :: Int }
```

Although doing so is frowned upon, as it makes the generated accessor functions partial. Also note I had to give the fields different names.

**Comment by hakonrossebo** [comment]
Thanks a lot for the clarification :)
